import type { Metadata } from "next";
import "./globals.css";
import Header from "./_Components/modules/Header";
import { User } from "@/public/Types/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch('http://localhost:4000/user', {cache: "no-cache"})
  const data = await  res.json()

  const res1 = await fetch('http://localhost:4000/categories', {cache: "no-cache"})
  const categories = await  res1.json()
  
  return (
    <html lang="en">
      <body className="flex flex-col mt-[45px] mx-[204px]">
        <Header userInfo={data} categories={categories}/>
        {children}
      </body>
    </html>
  );
}

